# config.yaml
project_name: "my-transformer"
train_dataset_path: "./data/TinyStoriesV2-GPT4-train.txt"
valid_dataset_path: "./data/TinyStoriesV2-GPT4-valid.txt"
output_bin_path: "./data/bin"
checkpoints_path: "./data/checkpoints"
epochs: 10
batch_size: 32
learning_rate: 1e-4
use_gpu: true
optimizer: "adamw"
vocab_size: 10000